name: Deploy-DEV

on:
    push:
        branches:
            - stable
    pull_request:
        branches:
            - stable
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Move dist to _site
              run: mv dist _site
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
    deploy:
        environment:
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
